In [22]:
import numpy as np
import pandas as pd

In [23]:
kiln = pd.read_csv("KILN PERFORMANCE.csv")

In [24]:
kiln.head(11)

,LOGO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KILN PERFORMANCE PROFILE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Hourly Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TAG,A_431FM1_F1,B_431FM2_F1,C_431BE1_JT,D_441CN1A_1B_TT01,E_451PC1_TT01,F_451PC1_TT04,G_461KL1_TT01,H_461KL1_PYRO_MTR,I_Kiln RPM,J_461KL1_IZ,K_461KL1_JZ_EM,L_471BU1_FT01,M_471BU1_PT01,N_461KL1_AT_NO
8,TAG DES,Kiln Feed,Kiln Feed,Kiln Feed BE KW,PH O/L TEMP.,Calciner Outlet Temp (TC)',TERITIARY AIR TEMP,Kiln I/L Temp,BURNING ZONE TEMP,Kiln rpm,Kiln current,kiln M.DRIVE POWER,PRIMARY AIR FLOW,PRIMARY AIR PRESSURE,Kiln I/L Gas Analyser NO
9,UNIT,tph,tph,Kw,°C,°C,°C,°C,°C,rpm,A,Kw,tph,mmWc,ppm
10,06/01/2019 00:00:00,0.0,299.4,102.0,354.4,962.2,974.1,1153.9,1135.5,5.0,388.0,383.3,3103.1,2398.6,283.7

In [25]:
kiln = kiln.drop([0,1,2,3,4,5,6])

In [26]:
kiln = kiln.iloc[:,[0,1,2,3,4,5,8,9,10,11,14]]

In [27]:
pre_heater_material = pd.read_csv("pre heater gas and material temp.csv")

In [28]:
pre_heater_material.head(11)

,LOGO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pre-heater gas& material temp profile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Hourly Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TAG,A_431FM1_F1,B_431FM2_F1,C_441CN1A_TT03,D_441CN1A_TT02,E_441CN1B_TT03,F_441CN1B_TT02,G_441CN2_TT01,H_441CN2_TT02,I_441CN3_TT01,J_441CN3_TT02,K_441CN4_TT01,L_441CN4_TT02,M_441CN5_TT01,N_441CN5_TT02
8,TAG DES,Kiln Feed,Kiln Feed,Cyn-1A Gas Temp,Cyn-1A Meterial Temp,Cyn-1B Gas Temp,Cyn-1B Meterial Temp,Cyn-2 Gas Temp,Cyn-2 Meterial Temp,Cyn-3 Gas Temp,Cyn-3 Meterial Temp,Cyn-4 Gas Temp,Cyn-4 Meterial Temp,Cyn-5 Gas Temp,Cylone -5 Metrial Temp (TC)'
9,UNIT,tph,tph,°C,°C,°C,°C,°C,°C,°C,°C,°C,°C,°C,°C
10,06/01/2019 00:00:00,0.0,299.4,341.0,350.1,361.9,348.1,378.7,378.9,598.1,594.8,782.5,806.1,916.7,1028.3

In [29]:
pre_heater_material = pre_heater_material.drop([0,1,2,3,4,5,6])

In [30]:
pre_heater_material = pre_heater_material.iloc[:,3:]

In [31]:
pre_heater_pressure = pd.read_csv("pre heater draft profile.csv")

In [32]:
pre_heater_pressure.head(15)

,LOGO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PRE-HEATER DRAFT PROFILE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Hourly Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TAG,A_431FM1_F1,B_431FM2_F1,C_431BE1_JT,D_441FN1_PT01,E_441CN1A_1B_PT01,F_441CN1A_PT03,G_441CN1B_PT03,H_441CN2_PT01,I_441CN3_PT01,J_441CN4_PT01,K_441CN5_PT01,L_451PC1_PT01,M_451PC1_PT03,N_461KL1_PT01
8,TAG DES,Kiln Feed,Kiln Feed,Kiln Feed BE KW,PH Fan Inlet Pressure,PH O/L DRAFT COMMON POINT,Cylone -1A Gas Outlet Pressure,Cylone -1B Gas outlet Pressure,Cylone -2 Gas Outlet Pressure,Cylone -3 Gas Outlet Pressure,Cyc 4 O/L Draft,Cylone -5 Gas Outlet Pressure,Calciner Outlet Pressure,Calciner Intlet Pressure,Kiln Inlet Pressure
9,UNIT,tph,tph,Kw,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc,mmWc
10,06/01/2019 00:00:00,0.1,304.4,103.9,-618.3,-516.9,-473.5,-467.7,-423.0,-338.7,-309.3,-269.9,-154.2,-42.4,-42.6
11,06/01/2019 01:00:00,0.1,305.7,102.5,-616.8,-515.4,-470.5,-469.7,-415.3,-340.6,-308.2,-267.5,-154.1,-39.1,-48.0
12,06/01/2019 02:00:00,0.1,303.9,102.5,-604.5,-505.2,-463.3,-460.3,-413.1,-334.3,-303.9,-264.7,-153.7,-37.3,-46.6
13,06/01/2019 03:00:00,0.1,304.2,102.5,-597.9,-503.0,-463.5,-457.9,-410.4,-337.3,-304.4,-265.5,-156.2,-42.3,-44.4
14,06/01/2019 04:00:00,0.1,304.3,102.5,-605.9,-506.6,-466.7,-460.2,-407.5,-333.7,-305.5,-262.9,-152.0,-34.0,-39.3

In [33]:
pre_heater_pressure = pre_heater_pressure.drop([0,1,2,3,4,5,6])

In [34]:
pre_heater_pressure = pre_heater_pressure.iloc[:,[12,13,14]]
pre_heater_pressure.head(11)

                 Unnamed: 12               Unnamed: 13          Unnamed: 14
7              L_451PC1_PT01             M_451PC1_PT03        N_461KL1_PT01
8   Calciner Outlet Pressure  Calciner Intlet Pressure  Kiln Inlet Pressure
9                       mmWc                      mmWc                 mmWc
10                    -154.2                     -42.4                -42.6
11                    -154.1                     -39.1                -48.0
12                    -153.7                     -37.3                -46.6
13                    -156.2                     -42.3                -44.4
14                    -152.0                     -34.0                -39.3
15                    -162.0                     -38.5                -50.6
16                    -100.3                     -38.8                -33.3
17                     -86.6                     -30.2                -29.4

In [35]:
pre_heater_fan = pd.read_csv("pre heater fan june 2019.csv")

In [36]:
pre_heater_fan.head(11)

,LOGO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pre-Heater Fan Performance Profile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Hourly Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,TAG,A_431FM1_F1,B_431FM2_F1,C_431BE1_JT,D_481FM3_FI,E_481FM1_FI,F_481FM2_FI,G_441FN1_TT01,H_441FN1_PT01,I_441FN1_TT02,J_441CN1A_1B_PT01,K_461KL1_PT01,L_441FN1_SZ,M_441FN1_KW_EM,N_441FN1_SPC_POWER
8,TAG DES,Kiln Feed,Kiln Feed,Kiln Feed BE KW,Kiln COAL TPH,PC COAL TPH,PC COAL FIRING,PH FAN I/L TEMP,PH Fan Inlet Pressure (PT),PH Fan O/L Temp,PH Fan Outlet DRAFT,Kiln Inlet Pressure (PT),PH Fan speed,PH Fan power EM,PH SPECIFIC POWER
9,UNIT,tph,tph,Kw,tph,tph,TPH,°C,mmWc,°C,mmWc,mmWc,rpm,Kw,Kw/T Clk
10,06/01/2019 00:00:00,0.0,299.4,102.0,7.3,10.6,0.0,194.4,-629.4,203.5,-527.7,-64.1,778.4,1098.1,4.2

In [37]:
pre_heater_fan = pre_heater_fan.drop([0,1,2,3,4,5,6])
bag = pd.read_csv("BAG FILTER.csv")
bag = bag.drop([0,1,2,3,4,5,6])
bag = bag.iloc[:,9]

In [38]:
pre_heater_fan = pre_heater_fan.iloc[:,[5,12]]
pre_heater_fan.head(11)

     Unnamed: 5   Unnamed: 12
7   E_481FM1_FI   L_441FN1_SZ
8   PC COAL TPH  PH Fan speed
9           tph           rpm
10         10.6         778.4
11         10.6         778.3
12         10.6         771.7
13         10.6         768.2
14         10.6         768.4
15         10.5         768.4
16          9.6         744.1
17          7.6         671.5

In [39]:
ph_coal_outlet = pd.concat([kiln,pre_heater_material,pre_heater_pressure,bag,pre_heater_fan],axis=1)

In [40]:
ph_coal_outlet.head(330)

,LOGO,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 9,Unnamed: 5,Unnamed: 12
7,TAG,A_431FM1_F1,B_431FM2_F1,C_431BE1_JT,D_441CN1A_1B_TT01,E_451PC1_TT01,H_461KL1_PYRO_MTR,I_Kiln RPM,J_461KL1_IZ,K_461KL1_JZ_EM,...,K_441CN4_TT01,L_441CN4_TT02,M_441CN5_TT01,N_441CN5_TT02,L_451PC1_PT01,M_451PC1_PT03,N_461KL1_PT01,I_421FN1_SZ,E_481FM1_FI,L_441FN1_SZ
8,TAG DES,Kiln Feed,Kiln Feed,Kiln Feed BE KW,PH O/L TEMP.,Calciner Outlet Temp (TC)',BURNING ZONE TEMP,Kiln rpm,Kiln current,kiln M.DRIVE POWER,...,Cyn-4 Gas Temp,Cyn-4 Meterial Temp,Cyn-5 Gas Temp,Cylone -5 Metrial Temp (TC)',Calciner Outlet Pressure,Calciner Intlet Pressure,Kiln Inlet Pressure,BAG HOUSE FAN RPM,PC COAL TPH,PH Fan speed
9,UNIT,tph,tph,Kw,°C,°C,°C,rpm,A,Kw,...,°C,°C,°C,°C,mmWc,mmWc,mmWc,rpm,tph,rpm
10,06/01/2019 00:00:00,0.0,299.4,102.0,354.4,962.2,1135.5,5.0,388.0,383.3,...,782.5,806.1,916.7,1028.3,-154.2,-42.4,-42.6,462.2,10.6,778.4
11,06/01/2019 01:00:00,0.0,300.1,101.7,353.5,954.7,1141.8,5.0,399.5,397.7,...,766.9,805.0,898.7,1019.9,-154.1,-39.1,-48.0,469.6,10.6,778.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,14/06/2019 10:00:00,0.0,51.2,17.6,370.0,825.9,750.0,1.2,77.7,60.1,...,740.5,716.0,796.5,879.3,48.6,-11.0,3.2,108.6,2.4,194.4
333,14/06/2019 11:00:00,0.0,0.0,0.0,372.6,790.8,750.0,0.1,0.3,2.4,...,701.8,646.1,730.8,745.2,48.5,-11.7,3.4,0.0,0.0,0.0
334,14/06/2019 12:00:00,0.0,52.1,43.9,384.9,774.3,750.0,0.3,128.1,13.8,...,677.9,623.8,701.0,712.7,70.3,2.7,29.4,145.0,0.1,87.4
335,14/06/2019 13:00:00,0.0,158.5,67.3,401.8,910.4,750.0,1.8,296.9,98.4,...,741.0,761.5,832.4,860.7,2.7,-26.2,-5.1,533.5,6.2,576.0
336,14/06/2019 14:00:00,0.0,220.4,82.6,347.7,920.3,750.0,3.3,389.6,268.2,...,763.1,776.0,877.5,915.4,-71.0,-36.7,-10.6,617.7,8.7,674.9

In [41]:
feed_150 = []
for o in range(len(ph_coal_outlet)):
    if o>=3 and float(ph_coal_outlet.iloc[o,1])+float(ph_coal_outlet.iloc[o,2])<150:
        feed_150.append(o)
print(feed_150)

[68, 325, 326, 327, 434, 435, 436, 437, 438, 439, 551, 552, 553, 554, 555, 556, 557, 558, 571, 572, 577, 578, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 751, 752, 753, 754, 1375, 1376, 1377, 1378, 1379, 1600, 1601, 1603, 1604, 1605, 1606, 1631, 1632, 1659, 1747, 1748, 1749, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2635, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2706, 2707, 2865, 2866, 2938, 3050, 3051, 3052, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3649, 3709, 3710, 3770, 3771, 3860, 3861, 3862, 4147, 4148, 4149, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4200, 4201, 4202, 4203, 4204, 4205, 4206, 4207, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 4216, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 4224, 4225, 4226, 4227, 4228, 4229, 4230, 4231, 4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4240, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4265, 4266, 4267, 4268, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4280, 4281, 4282, 4283, 4284, 4285, 4286, 4287, 4288, 4289, 4290, 4291, 4292, 4293, 4294, 4295, 4296, 4297, 4298, 4299, 4300, 4301, 4302, 4303, 4304, 4305, 4306, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4385, 4386, 4387, 4388, 4428, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4513, 4514, 5159, 5160, 5161, 5162, 5163, 5164, 5313, 5314, 5818, 5822, 5842, 5843, 5844, 5845, 5867, 5868, 5869, 5870, 5871, 5872, 5873, 5874, 5875, 5876, 5877, 5878, 5879, 5880, 5881, 5882, 5883, 5884, 5885, 5886, 5887, 5888, 5889, 5890, 5891, 5892, 5893, 5894, 5895, 5896, 5897, 5898, 5899, 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909, 5910, 5911, 5912, 5913, 5914, 5915, 5916, 5917, 5918, 5919, 5920, 5921, 5922, 5923, 5924, 5925, 5926, 5927, 5928, 5929, 5930, 5931, 5932, 5933, 5934, 5935, 5936, 5937, 5938, 5939, 5940, 5941, 5942, 5943, 5944, 5945, 5946, 5947, 5948, 5949, 5950, 5951, 5952, 5953, 5954, 5955, 5956, 5957, 5958, 5959, 5960, 5961, 5962, 5963, 5964, 5965, 5966, 5967, 5968, 5969, 5970, 5971, 5972, 5973, 5974, 5975, 5976, 5977, 5978, 5979, 5980, 5981, 5982, 5983, 5984, 5985, 5986, 5987, 5988, 5989, 5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6072, 6073, 6074, 6075, 6076, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6096, 6097, 6098, 6099, 6100, 6101, 6102, 6103, 6104, 6105, 6106, 6107, 6108, 6109, 6110, 6111, 6112, 6113, 6114, 6115, 6116, 6117, 6118, 6119, 6120, 6121, 6122, 6123, 6124, 6125, 6126, 6127, 6128, 6129, 6130, 6131, 6132, 6133, 6137, 6189, 6190, 6191, 6192, 6193, 6194, 6195, 6196, 6197, 6227, 6228, 6229, 6481, 6494, 6495, 6496, 6497, 6498, 6499, 6873, 6874, 7117, 7118, 7119, 7120, 7121, 7122, 7123, 7124, 7125, 7126, 7127, 7128, 7129, 7130, 7131, 7132, 7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7142, 7143, 7144, 7145, 7146, 7147, 7148, 7149, 7150, 7151, 7152, 7153, 7154, 7155, 7156, 7157, 7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165, 7166, 7167, 7168, 7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176, 7177, 7178, 7179, 7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187, 7188, 7189, 7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198, 7199, 7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209, 7210, 7211, 7212, 7213, 7214, 7215, 7216, 7217, 7218, 7219, 7220, 7221, 7222, 7223, 7224, 7225, 7226, 7227, 7228, 7229, 7230, 7231, 7232, 7233, 7234, 7235, 7236, 7237, 7238, 7239, 7240, 7241, 7242, 7243, 7244, 7245, 7246, 7247, 7248, 7249, 7250, 7251, 7252, 7253, 7254, 7255, 7256, 7257, 7258, 7259, 7260, 7261, 7262, 7263, 7264, 7265, 7266, 7267, 7268, 7269, 7270, 7271, 7272, 7273, 7274, 7275, 7276, 7277, 7278, 7279, 7280, 7281, 7282, 7283, 7284, 7285, 7286, 7287, 7288, 7289, 7290, 7291, 7292, 7293, 7294, 7295, 7296, 7297, 7298, 7299, 7300, 7301, 7302, 7303, 7304, 7305, 7306, 7307, 7308, 7309, 7310, 7311, 7312, 7313, 7314, 7315, 7316, 7317, 7318, 7319, 7320, 7321, 7322, 7323, 7324, 7325, 7326, 7327, 7328, 7329, 7330, 7331, 7332, 7333, 7334, 7335, 7336, 7337, 7338, 7339, 7340, 7341, 7342, 7343, 7344, 7345, 7346, 7347, 7348, 7349, 7350, 7351, 7352, 7353, 7354, 7355, 7356, 7357, 7358, 7359, 7360, 7361, 7362, 7363, 7364, 7365, 7366, 7367, 7368, 7369, 7370, 7371, 7372, 7373, 7374, 7375, 7376, 7377, 7378, 7379, 7380, 7381, 7382, 7383, 7384, 7385, 7386, 7387, 7388, 7389, 7390, 7391, 7392, 7393, 7394, 7395, 7396, 7397, 7398, 7399, 7400, 7401, 7402, 7403, 7404, 7405, 7406, 7407, 7408, 7409, 7410, 7411, 7412, 7413, 7414, 7415, 7416, 7417, 7418, 7419, 7420, 7421, 7422, 7423, 7424, 7425, 7426, 7427, 7428, 7429, 7430, 7431, 7432, 7433, 7434, 7435, 7436, 7437, 7438, 7439, 7440, 7441, 7442, 7443, 7444, 7445, 7446, 7447, 7448, 7449, 7450, 7451, 7452, 7453, 7454, 7455, 7456, 7457, 7458, 7459, 7460, 7461, 7462, 7463, 7464, 7465, 7466, 7467, 7468, 7469, 7470, 7471, 7472, 7473, 7474, 7475, 7476, 7477, 7478, 7479, 7480, 7481, 7482, 7483, 7484, 7485, 7486, 7487, 7488, 7489, 7490, 7491, 7492, 7493, 7494, 7495, 7496, 7497, 7498, 7499, 7500, 7501, 7502, 7503, 7504, 7505, 7506, 7507, 7508, 7509, 7510, 7511, 7512, 7513, 7514, 7515, 7516, 7517, 7518, 7519, 7520, 7521, 7522, 7523, 7524, 7525, 7526, 7527, 7528, 7529, 7530, 7531, 7532, 7533, 7534, 7535, 7536, 7537, 7538, 7539, 7540, 7541, 7542, 7543, 7544, 7545, 7546, 7547, 7548, 7549, 7550, 7551, 7552, 7553, 7554, 7555, 7556, 7557, 7558, 7559, 7560, 7561, 7562, 7563, 7564, 7565, 7566, 7567, 7568, 7569, 7570, 7571, 7572, 7573, 7574, 7575, 7576, 7577, 7578, 7579, 7580, 7581, 7582, 7583, 7584, 7585, 7586, 7587, 7588, 7589, 7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599, 7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609, 7610, 7611, 7612, 7613, 7614, 7615, 7616, 7617, 7618, 7619, 7620, 7621, 7622, 7623, 7624, 7625, 7626, 7627, 7628, 7629, 7630, 7631, 7632, 7633, 7634, 7635, 7636, 7637, 7638, 7639, 7640, 7641, 7642, 7643, 7644, 7645, 7646, 7647, 7648, 7649, 7650, 7651, 7652, 7653, 7654, 7655, 7656, 7657, 7658, 7659, 7660, 7661, 7662, 7663, 7664, 7665, 7666, 7667, 7668, 7669, 7670, 7671, 7672, 7673, 7674, 7675, 7676, 7677, 7678, 7679, 7680, 7681, 7682, 7683, 7684, 7685, 7686, 7687, 7688, 7689, 7690, 7691, 7692, 7693, 7694, 7695, 7696, 7697, 7698, 7699, 7700, 7701, 7702, 7703, 7704, 7705, 7706, 7707, 7708, 7709, 7710, 7711, 7712, 7713, 7714, 7715, 7716, 7717, 7718, 7719, 7720, 7721, 7722, 7723, 7724, 7725, 7726, 7727, 7728, 7729, 7730, 7731, 7732, 7733, 7734, 7735, 7736, 7737, 7738, 7739, 7740, 7741, 7742, 7743, 7744, 7745, 7746, 7747, 7748, 7749, 7750, 7751, 7752, 7753, 7754, 7755, 7756, 7757, 7758, 7759, 7760, 7761, 7762, 7763, 7764, 7765, 7766, 7767, 7768, 7769, 7770, 7771, 7772, 7773, 7774, 7775, 7776, 7777, 7778, 7779, 7780, 7781, 7782, 7783, 7784, 7785, 7786, 7787, 7788, 7789, 7790, 7791, 7792, 7793, 7794, 7795, 7796, 7797, 7798, 7799, 7800, 7801, 7802, 7803, 7804, 7805, 7806, 7807, 7808, 7809, 7810, 7811, 7812, 7813, 7814, 7815, 7816, 7817, 7818, 7819, 7820, 7821, 7822, 7823, 7824, 7825, 7826, 7827, 7828, 7829, 7830, 7831, 7832, 7833, 7834, 7835, 7836, 7837, 7838, 7839, 7840, 7841, 7842, 7843, 7844, 7845, 7846, 7847, 7848, 7849, 7850, 7851, 7852, 7853, 7854, 7855, 7856, 7857, 7858, 7859, 7860, 7861, 7862, 7863, 7864, 7865, 7866, 7867, 7868, 7869, 7870, 7871, 7872, 7873, 7874, 7875, 7876, 7877, 7878, 7879, 7880, 7881, 7882, 7883, 7884, 7885, 7886, 7887, 7888, 7889, 7890, 7891, 7892, 7893, 7894, 7895, 7896, 7897, 7898, 7899, 7900, 7901, 7902, 7903, 7904, 7905, 7906, 7907, 7908, 7909, 7910, 7911, 7912, 7913, 7914, 7915, 7916, 7917, 7918, 7919, 7920, 7921, 7922, 7923, 7924, 7925, 7926, 7927, 7928, 7929, 7930, 7931, 7932, 7933, 7934, 7935, 7936, 7937, 7938, 7939, 7940, 7941, 7942, 7943, 7944, 7945, 7946, 7947, 7948, 7949, 7950, 7951, 7952, 7953, 7954, 7955, 7956, 7957, 7958, 7959, 7960, 7961, 7962, 7963, 7964, 7965, 7966, 7967, 7968, 7969, 7970, 7971, 7972, 7973, 7974, 7975, 7976, 7977, 7978, 7979, 7980, 7981, 7982, 7983, 7984, 7985, 7986, 7987, 7988, 7989, 7990, 7991, 7992, 7993, 7994, 7995, 7996, 7997, 7998, 7999, 8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009, 8010, 8011, 8012, 8013, 8014, 8015, 8016, 8017, 8018, 8019, 8020, 8021, 8022, 8023, 8024, 8025, 8026, 8027, 8028, 8029, 8030, 8031, 8032, 8033, 8034, 8035, 8036, 8037, 8038, 8039, 8040, 8041, 8042, 8043, 8044, 8045, 8046, 8047, 8048, 8049, 8050, 8051, 8052, 8053, 8054, 8055, 8056, 8057, 8058, 8059, 8060, 8061, 8062, 8063, 8064, 8065, 8066, 8067, 8068, 8069, 8070, 8071, 8072, 8073, 8074, 8075, 8076, 8077, 8078, 8079, 8080, 8081, 8082, 8083, 8084, 8085, 8086, 8087, 8088, 8089, 8090, 8091, 8092, 8093, 8094, 8095, 8096, 8097, 8098, 8099, 8100, 8101, 8102, 8103, 8104, 8105, 8106, 8109, 8110, 8111, 8112, 8113, 8114, 8115, 8116, 8117, 8118, 8119, 8120, 8121, 8122, 8123, 8124, 8125, 8126, 8127, 8128, 8129, 8130, 8131, 8132, 8133, 8134, 8135, 8136, 8137, 8138, 8139, 8140, 8141, 8142, 8143, 8144, 8145, 8146, 8147, 8148, 8149, 8150, 8151, 8152, 8153, 8154, 8155, 8156, 8157, 8158, 8159, 8160, 8161, 8162, 8163, 8164, 8165, 8166, 8167, 8168, 8169, 8170, 8195, 8196, 8197, 8198, 8199, 8200, 8201, 8202, 8203, 8204, 8205, 8206, 8207, 8511, 8512, 8513, 8514, 8515, 8516, 8517, 8787, 8790]

In [42]:
for o in range(len(feed_150)):
    feed_150[o]=feed_150[o]+7
ph_coal_outlet = ph_coal_outlet.drop(feed_150)
ph_coal_outlet.to_csv("ph coal outlet.csv")